"""add personas table and link users to persona + onboarding flag

Revision ID: 07be463b5a62
Revises: ddec2359eacc
Create Date: 2026-08-26 17:56:13.402412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07be463b5a62'
down_revision: Union[str, None] = 'ddec2359eacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('users', sa.Column('persona_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'has_completed_onboarding', server_default=None)
    op.create_foreign_key(None, 'users', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'has_completed_onboarding')
    op.drop_column('users', 'persona_id')
    op.drop_table('personas')
    # ### end Alembic commands ###
